name: Notify Teams on Push, PR, and Merge

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Send Adaptive Card to Teams
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://middlewaretalentslimited.webhook.office.com/webhookb2/c04dd3b1-d304-465c-8de5-3b20c5e63080@118b2919-e434-405b-9f3c-3a829eba55f9/IncomingWebhook/b330747133af4f0d98b5b9e0b4fb1da9/225aaacb-3f40-48b2-a6c7-0f309a7f8c59/V27ZRot6_0dagnBFE6wCMxHdhE-3X1QYavY139KgIzVjE1'
          method: 'POST'
          contentType: 'application/json'
          data: |
            {
              "@type": "MessageCard",
              "@context": "https://schema.org/extensions",
              "summary": "GitHub Notification",
              "themeColor": "0078D7",
              "title": "GitHub Notification: ${{ github.event_name }}",
              "sections": [
                {
                  "activityTitle": "**Branch:** ${{ github.ref_name }}",
                  "activitySubtitle": "**Committer:** ${{ github.actor }}",
                  "facts": [
                    {
                      "name": "Commit Message",
                      "value": "${{ github.event.head_commit.message || 'N/A' }}"
                    },
                    {
                      "name": "PR Title",
                      "value": "${{ github.event.pull_request.title || 'N/A' }}"
                    },
                    {
                      "name": "PR Number",
                      "value": "${{ github.event.pull_request.number || 'N/A' }}"
                    }
                  ],
                  "markdown": true
                }
              ],
              "potentialAction": [
                {
                  "@type": "OpenUri",
                  "name": "View Commit/PR",
                  "targets": [
                    {
                      "os": "default",
                      "uri": "${{ github.event.head_commit.url || github.event.pull_request.html_url || '' }}"
                    }
                  ]
                }
              ]
            }
