name: Run Flow on Commit Only

on:
  push:
    branches:
      - main        # Change to your branch if needed
    paths:
      - '**/*'      # Run if any file changes

jobs:
  flow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Skip if this is a rerun triggered from the UI
      - name: Skip reruns
        if: ${{ github.event.workflow_run != null }}
        run: |
          echo "This workflow is a rerun triggered from UI. Exiting."
          exit 0

      - name: Run your flow
        run: |
          echo "New commit detected. Running the flow..."
          # Add your actual commands or scripts here
